#thymeleaf
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false

  jpa:
    show-sql: true

  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      properties:
        transport:
          tcp:
            connect_timeout: 120s